contigua:	
	# Compilando a implementacao da fila
	gcc -c pilha_contigua.c -o pilha_contigua.o
	
	# Compilando e gerando o executavel
	gcc main.c pilha_contigua.o -o main
	
	# Executando
	./main

    	gcc -c tad_vetor.c
	gcc main.c tad_vetor.o -o main